### ISSUE TITLE
Correct documentation to explain minimal inputs for bwa-meth subworkflow 

### ISSUE THREAD

**Issue by scoughlan2** [nf-core/methylseq#363] opened 2023-12-12 15:55 UTC
### Description of the bug

The  documentation [here](https://nf-co.re/methylseq/2.5.0#pipeline-summary) and [here](https://nf-co.re/methylseq/2.5.0/docs/usage#introduction) implies that bwa-meth can be run just by adding --aligner bwameth to a command line the one specified at [here](https://nf-co.re/methylseq/2.5.0/docs/usage#running-the-pipeline) .

 However the [iGenomes file](https://github.com/nf-core/methylseq/blob/2.5.0/conf/igenomes.config) doesn't have bwa-meth indices so that genome cant be used without running bwa-meth index on the genome. The documentation for the [genome flag](https://nf-co.re/methylseq/2.5.0/parameters) doesn't explain that it won't work with bwameth. Supplying just a local reference genome looks like it should work from [this code](https://github.com/nf-core/methylseq/blob/2.5.0/subworkflows/local/prepare_genome.nf#L39-L62) but according to this [bug](https://github.com/nf-core/methylseq/issues/352) , that doesn't work. 
 
 I had a successful run using the following parameters:

```
--input <samplesheet.csv>
--outdir ./results
--aligner bwameth 
--bwa_meth_index </path/to/bwa_meth_index_dir>
--fasta <genome.fa>
--fasta_index <genome.fa.fai>
--profile docker 
```

I would request that the documentation is updated to reflect that you can't use an iGenomes reference for bwameth (currently at least) and to explain what is needed to run the bwameth subworkflow.

### Command used and terminal output

Implication is that something like the code below can be used

```bash
nextflow run nf-core/methylseq --input ./samplesheet.csv --outdir ./results --genome GRCh38 --aligner bwameth -profile docker
```

However this results in the following error: 
```
ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_METHYLSEQ:METHYLSEQ:PREPARE_GENOME:SAMTOOLS_FAIDX (null)'

Caused by:
  Not a valid path value type: groovyx.gpars.dataflow.DataflowVariable (DataflowVariable(value=/ngi-igenomes/igenomes/Homo_sapiens/NCBI/GRCh38/Sequence/WholeGenomeFasta/genome.fa))

```

### System information

nfcore methylseq 2.5.0

**Comment by cjfields** [comment] 2024-02-01 03:29
I'm seeing this as well. I should also mention there appear to be a related issue with the `samtools faidx` reference indexing as well, but the workflow using `bismark` works fine.

**Comment by ewels** [comment] 2024-02-03 00:14
I think that the docs are fine, doing just `--aligner bwameth` did _use_ to work. The pipeline just built the reference index for you if not supplied. `--genome` was still used to supply the Fasta files to build it.

I think what this really boils down to is that there's a bug with reference index building with bwameth.

**Comment by ewels** [comment] 2024-02-03 00:16
Closing as a duplicate of https://github.com/nf-core/methylseq/issues/352

Feel free to disagree with me and we can reopen :)

**Closed by ewels** 2024-02-03 00:16 UTC
Labels: bug
