### ISSUE TITLE
errors version???

### ISSUE THREAD

**Issue by torres-HI** [nf-core/methylseq#480] opened 2024-12-02 23:12 UTC
### Description of feature

hi everyone

I have some problems with this pipeline, not sure what the problem is. 
1- Can some one guide to me to effectively running this pipeline,

2- Some one know where i can found a file with the alternative splicing genes known for mm10

thank you
Project `nf-core/methylseq` is currently stuck on revision: 2.7.1 -- you need to explicitly specify a revision with the option `-r` in order to use it
/var/spool/slurm/d/job4700351/slurm_script: line 42: docker/singularity: No such file or directory

**Comment by sateeshperi** [comment] 2024-12-04 15:27
try this command and of course, plz adjust as per your setup

```
nextflow run nf-core/methylseq -r 2.7.1 -profile test,singularity --outdir results
```

**Comment by torres-HI** [comment] 2024-12-04 22:28
here is the response, thanks for any advise to fix this issue


ERROR ~ Error executing process > 'NFCORE_METHYLSEQ:METHYLSEQ:TRIMGALORE
(2)'


Caused by:

  Failed to pull singularity image

    command: singularity pull  --name
depot.galaxyproject.org-singularity-trim-galore%3A0.6.10--hdfd78af_1.img.pulling.1733350699876
https://depot.galaxyproject.org/singularity/trim-galore%3A0.6.10--hdfd78af_1
> /dev/null

    status : 255

    hint   : Try and increase singularity.pullTimeout in the config
(current is "20m")

    message:

      INFO:    Downloading network image

      INFO:    Cleaning up incomplete download:
/mnt/lustre/koa/scratch/torres91/.apptainer/cache/cache/net/tmp_4292869819

      FATAL:   read tcp 10.3.13.2:35624->128.118.250.14:443: read:
connection reset by peer




 -- Check '.nextflow.log' file for details

ERROR ~ Pipeline failed. Please refer to troubleshooting docs:
https://nf-co.re/docs/usage/troubleshooting


 -- Check '.nextflow.log' file for details

**Comment by sateeshperi** [comment] 2024-12-05 06:10
Seems to be an issue with with your singularity setup and not necessarily an issue with the methylseq pipeline. 

I suggest you close this issue and reach out for help on nf-core slack in #help or #methylseq channels

**Comment by torres-HI** [comment] 2024-12-05 19:59
Thank you for your comment. However, I’ve been working with various nf-core
pipelines on the same cluster for over six months, using Singularity, and
none of them have caused any issues. This is the first time I’m
encountering problems.

Could you help me understand what might be different in this case?

Thanks again for your support!

**Comment by sateeshperi** [comment] 2024-12-06 03:03
from the log you posted it seems the issue is with downloading the trimgalore singularity container 

```
status : 255 hint : Try and increase singularity.pullTimeout in the config (current is "20m") message: INFO: Downloading network image INFO: Cleaning up incomplete download: /mnt/lustre/koa/scratch/torres91/.apptainer/cache/cache/net/tmp_4292869819 FATAL: read tcp 10.3.13.2:35624->128.118.250.14:443: read: connection reset by peer
```

my singularity experience is limited hence, I asked to post in slack channel so that you might get more appropriate help

**Comment by torres-HI** [comment] 2024-12-06 03:32
Ok, I'll check it out.

thank you so much

**Comment by sateeshperi** [comment] 2024-12-06 03:41
once you find a solution for your issue, kindly close this issue. Thank you

**Closed** 2024-12-17 03:44 UTC
